apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    argocd.argoproj.io/instance: sample-nginx
  name: nginx-svc
  namespace: nginx
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
